
export enum KeywordType {
    Var,
    Set,
    Const,
    Local,
    Function,
    Macro,
    Cleanup,
    Await,

    If,
    Else,
    In,
    While,
    For,
    Loop,
    Break,
    Continue,
    Return,
    ForEach,
    To,
    From,

    Debugger,
    As,
    Declare,
    Satisfy,
    Class,
    Private,
    Public,
    Throw,
}

export const Keywords: {
    [K in KeywordType]: string | string[];
} = {
    [KeywordType.Var]: "var",
    [KeywordType.Set]: "set",
    [KeywordType.Const]: "const",
    [KeywordType.Local]: "local",
    [KeywordType.Function]: "function",
    [KeywordType.Macro]: "function!",
    [KeywordType.Cleanup]: "cleanup",
    [KeywordType.Await]: "await",
    
    [KeywordType.If]: "if",
    [KeywordType.Else]: "else",
    [KeywordType.In]: "in",
    [KeywordType.While]: "while",
    [KeywordType.For]: "for",
    [KeywordType.Loop]: "loop",
    [KeywordType.Break]: "break",
    [KeywordType.Continue]: "continue",
    [KeywordType.Return]: "return",
    [KeywordType.ForEach]: ["for", "each"],
    [KeywordType.To]: "to",
    [KeywordType.From]: "from",
    
    [KeywordType.Debugger]: "debugger",
    [KeywordType.As]: "as",
    [KeywordType.Declare]: "declare",
    [KeywordType.Satisfy]: "satisfy",
    [KeywordType.Class]: "class",
    [KeywordType.Private]: "private",
    [KeywordType.Public]: "public",
    [KeywordType.Throw]: "throw",
};
