import { lexer, LexerError, parse } from "@narralang/core";

export interface CompileOk {
    ok: true;
    typescript: string;
}

export interface CompileErr {
    ok: false;
    error: Error;
}

export type CompileResult = CompileOk | CompileErr;

/**
 * Phase-1 compiler: validate .nls and emit a TypeScript module that exports the parsed AST as data.
 * Full static codegen (DSL -> scene TS) will replace this emitter later.
 */
export function compileNlsToTypeScript(source: string, sourcePath = "input.nls"): CompileResult {
    const tokens = lexer(source);
    if (LexerError.isLexerError(tokens)) {
        return { ok: false, error: new Error(tokens.message) };
    }
    try {
        const { nodes } = parse(tokens, { sourceText: source, enhancedErrors: true });
        const json = JSON.stringify(nodes, null, 2) as string;
        const header =
            "/**\n" +
            ` * @generated by @narralang/nlc from ${sourcePath.replace(/\*/g, "")}\n` +
            " * Phase-1: AST snapshot. Static expression codegen is not implemented yet.\n" +
            " */\n";
        const ts =
            `${header}` +
            "import type { ParsedNode } from \"@narralang/core\";\n\n" +
            `export const nlsAst: ParsedNode[] = ${json};\n`;
        return { ok: true, typescript: ts };
    } catch (e) {
        const err = e instanceof Error ? e : new Error(String(e));
        return { ok: false, error: err };
    }
}
